name: 'Rsync'

on:
  push:
    branches:
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  main:
    runs-on: [self-hosted,FlipperZeroShell]
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]
          then
            git submodule status \
              || git checkout `git rev-list --max-parents=0 HEAD | tail -n 1`
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}


      - name: 'Make artifacts directory'
        run: |
          test -d artifacts && rm -rf artifacts || true
          mkdir artifacts

      - name: 'Generate suffix and folder name'
        id: names
        run: |
          REF=${{ github.ref }}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            REF=${{ github.head_ref }}
          fi
          BRANCH_OR_TAG=${REF#refs/*/}
          SHA=$(git rev-parse --short HEAD)

          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            SUFFIX=${BRANCH_OR_TAG//\//_}
          else
            SUFFIX=${BRANCH_OR_TAG//\//_}-$(date +'%d%m%Y')-${SHA}
          fi

          echo "WORKFLOW_BRANCH_OR_TAG=${BRANCH_OR_TAG}" >> $GITHUB_ENV
          echo "DIST_SUFFIX=${SUFFIX}" >> $GITHUB_ENV
          echo "::set-output name=artifacts-path::${BRANCH_OR_TAG}"
          echo "::set-output name=suffix::${SUFFIX}"
          echo "::set-output name=short-hash::${SHA}"
          echo "::set-output name=default-target::${DEFAULT_TARGET}"

      - name: 'Upload artifacts to update server'
        if: ${{ !github.event.pull_request.head.repo.fork }}
        run: |
          echo "${{ secrets.RSYNC_DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -avzP --mkpath \
              -e 'ssh -p ${{ secrets.RSYNC_DEPLOY_PORT }} -i ./deploy_key' \
              artifacts/ ${{ secrets.RSYNC_DEPLOY_USER }}@${{ secrets.RSYNC_DEPLOY_HOST }}:"${{ secrets.RSYNC_DEPLOY_BASE_PATH }}${{steps.names.outputs.artifacts-path}}/"

